//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDA1
    {
        public int DocEntry { get; set; }
        public string BandejaCode { get; set; }
        public int DocLinea { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string UsuarioCodeIngreso { get; set; }
        public string MotivoIngreso { get; set; }
        public Nullable<System.DateTime> FechaAutorizado { get; set; }
        public Nullable<bool> Autorizado { get; set; }
        public string UsuarioCodeAutoriza { get; set; }
        public string MotivoRechazo { get; set; }
        public Nullable<int> LineaItem { get; set; }
        public Nullable<decimal> ValorSolicitado { get; set; }
        public Nullable<decimal> ValorRegla { get; set; }
        public Nullable<decimal> MargenRegla { get; set; }
    }
}
