//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITM4
    {
        public int FamiliaCode { get; set; }
        public string FamiliaNombre { get; set; }
        public Nullable<decimal> Margen { get; set; }
        public Nullable<decimal> DescVolumen { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<decimal> FactorPrecio { get; set; }
        public string FamiliaNombreCorto { get; set; }
        public Nullable<int> Correlativo { get; set; }
    }
}
