//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITR1
    {
        public string ProdCode { get; set; }
        public string ProdCodeRef { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string ProdNombreRef { get; set; }
        public string TipoCode { get; set; }
    }
}
