//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPC1
    {
        public string ListaCode { get; set; }
        public string ProdCode { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string ProdNombre { get; set; }
        public string FamiliaNombre { get; set; }
        public string OrigenNombre { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Margen { get; set; }
        public Nullable<decimal> PrecioNormal { get; set; }
    }
}
