//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNU1
    {
        public short IdSubMenu { get; set; }
        public Nullable<short> FK_MenuMain { get; set; }
        public string keyMenu { get; set; }
        public string Nombre { get; set; }
        public string Caption { get; set; }
        public string url { get; set; }
        public string icon { get; set; }
    }
}
