//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBDA
    {
        public int DocEntry { get; set; }
        public string BandejaCode { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string UsuarioCodeIngreso { get; set; }
        public string SocioCode { get; set; }
        public string RazonSocial { get; set; }
        public string VendedorCode { get; set; }
        public Nullable<System.DateTime> FechaAproRech { get; set; }
        public string MotivoRech { get; set; }
        public string UsuarioCodeAproRech { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> Autorizado { get; set; }
    }
}
