//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPKG
    {
        public int DocEntry { get; set; }
        public string DocEstado { get; set; }
        public Nullable<int> DocTipo { get; set; }
        public Nullable<System.DateTime> DocFecha { get; set; }
        public string SocioCode { get; set; }
        public string RazonSocial { get; set; }
        public string VendedorCode { get; set; }
        public string UsuarioCode { get; set; }
        public string UsuarioNombre { get; set; }
        public string UsuarioCodeResponsable { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Version { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public string BodegaCode { get; set; }
        public string UsuarioResponsable { get; set; }
        public Nullable<bool> RetiraCliente { get; set; }
        public Nullable<int> BaseTipo { get; set; }
        public Nullable<int> DocRendicion { get; set; }
    }
}
