//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORUT
    {
        public int DocEntry { get; set; }
        public string DocEstado { get; set; }
        public Nullable<int> DocTipo { get; set; }
        public Nullable<System.DateTime> DocFecha { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Observaciones { get; set; }
        public string EstadoOperativo { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseTipo { get; set; }
        public string Vehiculo { get; set; }
        public string scenario_token { get; set; }
        public string schema_name { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioCode { get; set; }
        public string Version { get; set; }
        public string UsuarioNombre { get; set; }
    }
}
