//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKG1
    {
        public int DocEntry { get; set; }
        public int DocLinea { get; set; }
        public string ProdCode { get; set; }
        public string ProdNombre { get; set; }
        public string MarcaNombre { get; set; }
        public string RefrigeraNombre { get; set; }
        public string OrigenNombre { get; set; }
        public string BodegaCode { get; set; }
        public Nullable<decimal> CantidadSolicitada { get; set; }
        public Nullable<decimal> CantidadReal { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseLinea { get; set; }
        public string TieneReceta { get; set; }
        public string FrmtoVentaNombre { get; set; }
        public Nullable<int> Cajas { get; set; }
        public Nullable<decimal> KilosPorCaja { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public Nullable<decimal> Tolerancia { get; set; }
        public Nullable<decimal> Completado { get; set; }
        public Nullable<int> BaseTipo { get; set; }
        public Nullable<int> DocTipo { get; set; }
        public string TipoCode { get; set; }
        public Nullable<decimal> PrecioFinal { get; set; }
    }
}
