//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PKG3
    {
        public int DocEntry { get; set; }
        public int DocLinea { get; set; }
        public string ProdCode { get; set; }
        public string ProdNombre { get; set; }
        public string BodegaCode { get; set; }
        public Nullable<decimal> CantidadSolicitada { get; set; }
        public Nullable<decimal> CantidadReal { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseLinea { get; set; }
        public string ProdTipo { get; set; }
        public Nullable<int> BaseTipo { get; set; }
        public Nullable<int> DocTipo { get; set; }
        public string ProdCodeRefGlosa { get; set; }
        public string TipoCode { get; set; }
    }
}
