//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class REN2
    {
        public int DocEntry { get; set; }
        public int DocLinea { get; set; }
        public string ProdCode { get; set; }
        public string ProdNombre { get; set; }
        public string BodegaCode { get; set; }
        public Nullable<decimal> CantidadSolicitada { get; set; }
        public Nullable<decimal> CantidadReal { get; set; }
        public Nullable<decimal> CantidadRendida { get; set; }
        public string ProdTipo { get; set; }
        public string ProdCodeRef { get; set; }
        public string ProdNombreRef { get; set; }
        public string TipoCode { get; set; }
        public Nullable<int> Orden { get; set; }
        public string ProdCodeGroup { get; set; }
        public Nullable<int> Posicion { get; set; }
    }
}
