//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCP13
    {
        public int IdHistorial { get; set; }
        public string SocioCode { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public string Cambios { get; set; }
        public string Usuario { get; set; }
    }
}
