//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCP11_tmp
    {
        public int Id { get; set; }
        public string SocioCode { get; set; }
        public string SocioNombre { get; set; }
        public string Documento { get; set; }
        public string Serie { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Vencimiento { get; set; }
        public Nullable<decimal> V91 { get; set; }
        public Nullable<decimal> V90 { get; set; }
        public Nullable<decimal> V60 { get; set; }
        public Nullable<decimal> V30 { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
