//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colonos.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRX1
    {
        public int DocEntry { get; set; }
        public int DocLinea { get; set; }
        public string ProdCode { get; set; }
        public string ProdNombre { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string MedidaCode { get; set; }
        public Nullable<decimal> CantidadSolicitada { get; set; }
    }
}
